### ISSUE TITLE
Negative value issue

### ISSUE THREAD

**Issue by o3o** [symmetryinvestments/xlsxreader#8]
I modify cell `F13` of "multitable.xlsx" worksheet "wb1", from `=E13*2` to `=-E13*2` (then the value becomes -26.74), then

```
$ dub test

\std/variant.d(1735): [unittest] Variant: attempting to use incompatible types immutable(char)[] and double
std.variant.VariantException@std/variant.d(1735): Variant: attempting to use incompatible types immutable(char)[] and doubl
```
Thank you very much

**Comment by burner** [comment]
thank you for the bug report

**Comment by burner** [comment]
https://github.com/symmetryinvestments/xlsxreader/releases/tag/v1.2.2 code.dlang.org should pick up the new version any minute now

**Comment by o3o** [comment]
Great, thank you very much!

**Comment by burner** [comment]
always, keep the issues coming
